apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80       # Service portu
      targetPort: 3000  # Container'daki uygulamanın portu
  type: NodePort
